parameters:
    price.symbols:
        - 'BTCEUR'
        - 'ETHEUR'
        - 'LTCEUR'
    binance.api.hosts:
        - 'https://api4.binance.com'
        - 'https://api3.binance.com'
        - 'https://api2.binance.com'
        - 'https://api1.binance.com'
        - 'https://api4.binance.com'
        - 'https://api.binance.com'
        - 'https://api-gcp.binance.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
